# where you put the network and density fles
data_folder: "./data/"
network_name: "Seattle_road_network.net.xml"
edges_name: "./output/seattlecomp0.txt"
info_name: "Edge_veh_od_psrc_convert20per.xml"
edges_to_remove_name: "./output/zero_density_edgeID.txt"

# feature that you'd like to read, e.g, density
feature: "density"
# interval start time in seconds upto two decimal points (for eg. 8 AM => 8)
interval_begin: 0
# interval end time in seconds # not used but here if required (for eg. 8 PM => 20)
interval_end: 23