# where you put the network and density files
data_folder: "./data/"
network_name: "Seattle_network_reformed 24Apr02.net.xml"
edges_name: "./output/seattlecomp0.txt"  # if network is changed run check_handler line 14
info_name: "edge_data_output_hour.xml"

#predetermined_regions_folder: "./data/config data/config for exported results/results-sep highways" ## for exported results
#predetermined_regions_folder: "./data/config data/config for normal segmentation/side regions" ## for having only highways as one predetermined segment
predetermined_regions_folder: "./data/config data/manual segmentation/7regions"
#predetermined_regions_folder: "./data/config data/config for segmentation with predetermined regions/side regions"
minor_links: "./data/config data/minor_edgeID.txt"  # links with very low priorities (alleys) can be removed.
edges_to_remove_name: "./data/config data/config for segmentation with predetermined regions/marginal_edgeID.txt"
# Also, we might need some other edges to be removed

# feature that you'd like to read, e.g, density  ---- in the codes it's usually referred to density
feature: "laneDensity"
#feature: "occupancy"
#feature: "sampledSeconds"

# interval start and end hour(for eg. 8 AM => 8)
interval_begin: 8
interval_end: 9