# where you put the network and density files
data_folder: "./data/"
network_name: "Seattle_road_network.net.xml"
edges_name: "./output/seattlecomp0.txt"
#info_name: "Edgetest_6_0411_2_0.xml"  # old 1hour output
info_name: "edge_data_output_hour.xml"


minor_links: "./data/config data/minor_edgeID.txt"
## for having the whole network
#predetermined_regions_folder: "./data/config data/config for segmentation with predetermined regions/side regions"
#edges_to_remove_name: "./data/config data/config for segmentation with predetermined regions/marginal_edgeID_new_simulation.txt"

## for having only the downtown/whole network without predetermined segments
predetermined_regions_folder: "./data/config data/config for normal segmentation/side regions"
edges_to_remove_name: "./data/config data/config for normal segmentation/marginal_edgeID_new_simulation.txt"
#edges_to_remove_name: "./data/config data/config for normal segmentation/marginal_edgeID_highways_and_tunnels.txt"
####edges_to_remove_name: "./data/config data/config for normal segmentation/marginal_edgeID_exclude_downtown0.txt"
#edges_to_remove_name: "./data/config data/config for normal segmentation/marginal_edgeID_exclude_downtown1.txt"


# feature that you'd like to read, e.g, density
feature: "laneDensity"
#feature: "occupancy"
# interval start time in seconds up to two decimal points (for eg. 8 AM => 8)
interval_begin: 8
# interval end time in seconds # not used but here if required (for eg. 8 PM => 20)
interval_end: 9