# where you put the network and density files
data_folder: "./data/"
network_name: "Seattle_road_network.net.xml"
edges_name: "./output/seattlecomp0.txt"
info_name: "edge_data_output_min.pickle"


minor_links: "./data/config data/for feature plotting/minor_edgeID.txt"
#minor_links: "./data/config data/for feature plotting/minor_edgeID empty.txt"
#minor_links: "./data/config data/for feature plotting/major_edgeID.txt"
predetermined_regions_folder: "./data/config data/for feature plotting/side regions"
edges_to_remove_name: "./data/config data/for feature plotting/marginal_edgeID.txt"


# feature that you'd like to read, e.g, density
#feature: "sampledSeconds"
feature: "laneDensity"
#feature: "laneDensity"
interval_begin: 18000
interval_end: 41400
#interval_end: 36000