
data_folder: "./data/"
network_name: "Seattle_network_reformed 24Apr02.net.xml"
edges_name: "./output/seattlecomp0.txt"
info_name: "edge_data_output_hour.xml"
minor_links: "./data/config data/minor_edgeID.txt"
#minor_links: "./data/config data/empty.txt"
#predetermined_regions_folder: "./data/config data/config for exported results/results-sep highways"
predetermined_regions_folder: "./data/config data/manual segmentation/7regions"
edges_to_remove_name: "./data/config data/config for segmentation with predetermined regions/marginal_edgeID.txt"
#predetermined_regions_folder: "./data/config data/test"
#edges_to_remove_name: "./data/config data/config for exported results/marginal_edgeID.txt"

feature: "laneDensity"  # or "occupancy" or "sampledSeconds"
interval_begin: 8
interval_end: 9


pq_input_folder: "output/pq_input/"
trip_info: "data/tripinfo_output.xml"
veh_route: "data/vehroute_output.xml"
demand_file: "data/adjusted_alaskanway_od2trips_psrc_vehicle_trips_converted_taz_calibrated_V3.rou.xml"
veh_route_time: "data/vehRouteTime_output.pickle"
veh_route_time_cong: "data/vehRouteTime_output_congested.pickle"
signal_info_adr: "data/signal_report108000_144000.csv"

# to be used in config.csv
model_type: 'PQ'
time_interval (s): '1'
simulation_steps: '25200'  # simulation end time // time interval
demand_stop_step: '18000'  # demand stop end time // time interval
min_outflow_zero: '1'
pseudo_region_included: '1'  # '1' means True
# to be used in demand.mat
sim_start: '18000'  # should match .sumocfg file

