# where you put the network and density files
data_folder: "./data/"
network_name: "Seattle_road_network.net.xml"
edges_name: "./output/seattlecomp0.txt"
info_name: "edge_data_output_hour.xml"

#
trip_info: "data/tripinfo_output.xml"
veh_route: "data/vehroute_output.xml"
pq_input_folder: "output/pq_input/"

#
model_type: 'PQ'
time_interval (s): '0.1'
simulation_steps: '324000'
deman_stop_step: '216000'

minor_links: "./data/config data/minor_edgeID.txt"
## for exported results
predetermined_regions_folder: "./data/config data/config for exported results/results"
edges_to_remove_name: "./data/config data/config for exported results/marginal_edgeID.txt"


# feature that you'd like to read, e.g, density
#feature: "laneDensity"
feature: "occupancy"
#feature: "sampledSeconds"
# interval start time in seconds up to two decimal points (for eg. 8 AM => 8)
interval_begin: 8
# interval end time in seconds # not used but here if required (for eg. 8 PM => 20)
interval_end: 9